// Remove this line as it creates a circular import
// import { POSTS, USERS_FOR_RIGHT_PANEL } from './utils/db/dummy';

export const POSTS = [
	{
		_id: "1",
		text: "love in the family 😍",
		img: "/posts/post1.png",
		user: {
			username: "reza",
			profileImg: "/avatars/boy1.png",
			fullName: "reza khorrami",
		},
		comments: [
			{
				_id: "1",
				text: "Nice picture",
				user: {
					username: "fahmideh",
					profileImg: "/avatars/girl1.png",
					fullName: "fahmideh khorrami",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "2",
		text: "How you guys doing? 😊",
		user: {
			username: "ali",
			profileImg: "/avatars/boy2.png",
			fullName: "ali khorrami",
		},
		comments: [
			{
				_id: "1",
				text: "Nice picture",
				user: {
					username: "sara",
					profileImg: "/avatars/girl2.png",
					fullName: "sara khorrami",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "3",
		text: "Astronaut in a room of drawers, generated by Midjourney. 🚀",
		img: "/posts/post2.png",
		user: {
			username: "ali",
			profileImg: "/avatars/boy3.png",
			fullName: "ali khorrami",
		},
		comments: [],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894", "6658s895", "6658s896"],
	},
	{
		_id: "4",
		text: "I'm learning GO this week. Any tips? 🤔",
		img: "/posts/post3.png",
		user: {
			username: "sara",
			profileImg: "/avatars/girl3.png",
			fullName: "sara khorrami",
		},
		comments: [
			{
				_id: "1",
				text: "Nice picture",
				user: {
					username: "ali",
					profileImg: "/avatars/boy3.png",
					fullName: "ali khorrami",
				},
			},
		],
		likes: [
			"6658s891",
			"6658s892",
			"6658s893",
			"6658s894",
			"6658s895",
			"6658s896",
			"6658s897",
			"6658s898",
			"6658s899",
		],
	},
];

export const USERS_FOR_RIGHT_PANEL = [
	{
		_id: "1",
		fullName: "reza khorrami",
		username: "reza",
		profileImg: "/avatars/boy2.png",
	},
	{
		_id: "2",
		fullName: "fahmideh khorrami",
		username: "fahmideh",
		profileImg: "/avatars/girl1.png",
	},
	{
		_id: "3",
		fullName: "ali khorrami",
		username: "ali",
		profileImg: "/avatars/boy3.png",
	},
	{
		_id: "4",
		fullName: "sara khorrami",
		username: "sara",
		profileImg: "/avatars/girl2.png",
	},
];

// Remove these console.log statements
// console.log(POSTS);
// console.log(USERS_FOR_RIGHT_PANEL);
